# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Andrew Richardson
tagline:          
description:      'iOS Developer & Student'
url:              http://andrewr.me

author:
  name:           'Andrew Richardson'
  url:            https://twitter.com/nosdrew

paginate:         5

# Custom vars
github:           https://github.com/aricha
twitter:          https://twitter.com/nosdrew
linkedin:         http://ca.linkedin.com/in/aricha
email:            contact@andrewr.me

assets:
  sources:
    - _assets/images
    - _assets/js
    - _assets/css

exclude: [
  'node_modules',
  'bower_components',
  'Gruntfile.js',
  'package.json',
  'bower.json',
  'requirements.txt',
  'Gemfile',
  'Gemfile.lock',
  'README.md',
  'env',
  'tmp'
]